version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    env_file:
      - ../application/.env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
