version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: node-app-dev
    ports:
      - "3000:3000"
    volumes:
      - ../application:/app
      - /app/node_modules
    env_file:
      - ../application/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
